// URLs
:openshift-console-url: {openshift-host}/dashboards
:fuse-documentation-url: https://access.redhat.com/documentation/en-us/red_hat_fuse/{fuse-version}/
:amq-documentation-url: https://access.redhat.com/documentation/en-us/red_hat_amq/{amq-version}/

//attributes
:title: 1 - Create and deploy your first Apache Camel K Integration
:standard-fail-text: Verify that you followed all the steps. If you continue to have issues, contact your administrator.
:bl: pass:[ +]

[id='1-create-and-deploy-your-first-integration']
= {title}

Create a simple link:https://camel.apache.org/camel-k/latest/index.html[Apache Camel K, window="_black"] integration to learn about important features, before working with more complex examples.

In this Solution Pattern, you will create a simple Greeter application that sends the message 'Hello, customer!' every few seconds.

[type=walkthroughResource,serviceName=openshift]
.Red Hat OpenShift
****
* link:{openshift-console-url}[Console, window="_blank"]
* link:https://docs.openshift.com/dedicated/4/welcome/index.html/[OpenShift Documentation, window="_blank"]
* link:https://blog.openshift.com/[OpenShift Blog, window="_blank"]
****

[type=walkthroughResource]
.Microsoft Visual Studio Code
****
* link:https://code.visualstudio.com/[VS Code, window="_blank"]
* link:https://code.visualstudio.com/docs[VS Code Documentation, window="_blank"]
****

:sectnums:

[time=5]
[id='creating-a-project']
== Creating a project
:task-context: creating-projects

WARNING: You must ask your cluster administrator to add the Camel K Operator to your cluster before perforing this Solution Pattern. 
// This IPT uber-operator will make this task obsolete when it becomes available.

****
*Creating a new project in OpenShift*
****

Follow these steps to create a new project.

. Go to the link:{openshift-console-url}[OpenShift Console, window="_blank"].
. Create a new project named `camel-basic`. 
.. Go to *Home* -> *Projects*.
.. Click the *Create Project* button.
. Monitor the OpenShift Console until a green check mark is displayed next to the new project.

[type=verification]
Look at the link:openshift-console-url: {openshift-host}/projects[OpenShift, window="_blank"] console. Do you see your newly created project displayed in the *Projects* list?

[type=verificationFail]
{standard-fail-text}

// end::task-creating-projects[]

[time=15]
[id='creating-a-project-in-vscode']
== Creating your project in VS Code or your Preferred IDE
:task-context: vs-code

Follow these steps on your local machine to create and deploy your integration in your preferred IDE.

The following procedure applies to using VS Code or Red Hat Code Ready Workspaces to create and deploy your integration.

. Install the link:https://marketplace.visualstudio.com/items?itemName=redhat.vscode-didact[Didact extension by Red Hat].
. Install the link:https://marketplace.visualstudio.com/items?itemName=redhat.apache-camel-extension-pack[Extension Pack for Apache Camel by Red Hat].
. Select the *Didact Tutorials* view.
.. Navigate to *Apache Camel K* -> *Starting a new Camel K Route* Solution Pattern. 
.. Swipe right to 
.. Click the *Start Didact Tutorial* button.
. Follow the steps in the `Starting a new Camel K Route` tutorial.

{bl}
Or, use your preferred development environment with access to Camel K to create and deploy your integration.

. Open a new terminal window.
. Ensure that you have access to the `kamel` command-line tool and that it is connected to your running OpenShift instance by typing `kamel version`. (See the link:https://camel.apache.org/camel-k/latest/installation/installation.html[Apache Camel K Installation documentation for help.])
. Type `kamel init Greeter.java` to create a new Java route that puts a message in the log once per second.
. Type `kamel run Greeter.java` to start the Integration.
. To verify that the integration is running, type `kamel get` to get a list of the integrations currently running or starting up.
. When the integration is in the status *Running*, you can view the log for the integration by typing `kamel log Greeter`.

{bl}
Return to Solution Explorer when you are done.

[type=verification]
Look at the link:openshift-console-url: {openshift-host}/dashboards[OpenShift, window="_blank"] console. Drill down into the `Operators->Installed Operators` list for the `camel-basic` project. Do you see your new integration in the *Integration* list?

[type=verificationFail]
{standard-fail-text}

// end::task-vscode[]

[time=5]
[id='check-openshift-for-integration']
== Find Your Running Camel K Integration
:task-context: run-camel

Follow these steps to verify that your integration is running in the OpenShift console.

. Open the OpenShift link:{openshift-host}/console[Console, window="_blank"]
. In the `Workloads->Pods` list, look for a pod that starts with `greeter-` and click on it.
. Click on the Logs tab and view the running log for your route. You should see similar output to what you witnessed in your IDE or terminal window.

[type=verification]
Look at the link:openshift-console-url: {openshift-host}/dashboards[OpenShift, window="_blank"] console. Drill down into the `Workloads->Pods` list for the `greeter-` pod and look at its log. Do you see the same messages you saw in your IDE?

[type=verificationFail]
{standard-fail-text}

// end::run-camel[]
